### ISSUE TITLE
Hint is not omitted.

### ISSUE THREAD

**Issue by huandney** [ruin1990/AnkiTemplate#1]
Hi,
When we add a Hint in cloze, that Hint remains after the reveal:

![Animação](https://user-images.githubusercontent.com/19948348/150613615-4a0fc897-109b-4a17-8453-1fa628de752a.gif)

**Comment by huandney** [comment]
Solution thanks to @kleinerpirat

```
$(".cloze").each(function () {
  $(this).attr("tabindex", idx + 10000); //for auto scroll
  $(this).attr("answer", "off");
  let src_html = $(this).html(); // line 416 from front.html
  let [answer, hint] = arr[idx].split("::", 1);
  $(this).html(
    `<div class="ruin_quiz" style="display:inline;">${
      hint ? `[${hint}]` : src_html
    }</div><div  class="ruin_answer" style="display:none;">${answer}</div>`
  );
  idx++;
});
```

**Comment by ruin1990** [comment]
Oh, thanks.
I am currently mainly troubled by some bugs that will affect mathjax in this code. I can only join the main branch when I get it done.
My test code: 
```
tset{{c1::sdfsad}}f{{c1::sd::sd}}af
\(\frac { {{c1::a-c::1234}} } { {{c1::b+1::4444}} }\) sdfff
```

**Comment by huandney** [comment]
Really, there is this problem, I didn't realize it because I use katex:
https://ankiweb.net/shared/info/1087328706

It just has a screen flickering issue, other than that it works perfectly.

**Comment by ruin1990** [comment]
Hi, I fix the hint bug. Could you please test it? [ankiweb](https://ankiweb.net/shared/info/457099967)
If you have changed my clozeadv template, remember to back it up before you test, so as not to lose your changes

In addition, the Katex you used is awesome, I think maybe you can combine the front code of the ClozeAdv template on the basis of his template, it will be perfect.

**Comment by huandney** [comment]
It seems to be working perfectly, I'll do more tests if I find something I report here!

By the way, next update you could add the option of multiple shortcuts for the same function:

```
var shortcuts = {
	"next": {
		"name": "Tab",
		"keycodes": ["Tab", "KeyW"],
	},
	"previous": {
		"name": "Backquote",
		"keycodes": ["Backquote", "KeyQ"],
	}
};
```
And then further down use [Array.prototype.includes() 1](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes):

```
document.addEventListener("keydown", (event) => {
  if (shortcuts.next.keycodes.includes(event.code)) {
    event.preventDefault();
    revealNext();
  } else if (shortcuts.previous.keycodes.includes(event.code)) coverPrevious();
});
```

Changing the subject, I wanted to know the reason behind not automatically flipping the card that has MathJax blocks?

**Comment by huandney** [comment]
I use a script to randomize lists, and I was having a problem revealing these randomized lists, they weren't revealed in order:

![Antes](https://user-images.githubusercontent.com/19948348/155059444-6dcb3a37-e4b5-4749-b9c8-4317024b9ea2.gif)

I reverted the `function revealNext()` to the previous version, and apparently it's working fine:

![Depois](https://user-images.githubusercontent.com/19948348/155059611-22f9a5a2-4342-43b1-8130-c29d3cf0be06.gif)

**Comment by huandney** [comment]
Just to inform.
I found a possible bug, but it's something very specific. Card did not automatically flip:

![flip](https://user-images.githubusercontent.com/19948348/155088233-10aff389-baa1-42ca-b825-3c0fe81e0c3a.gif)

Details:
- This only occurred when the clozes was inside the quote above
- Curiously, if I disable `max-width: 55em;` inside `.win .text {}` in css it doesn't happen


After changing
`if(cloze_num<=0 && !hasScrollbar() && have_mathjax_content==false)` to `if(cloze_num<=0 && have_mathjax_content==false)`
it worked fine again:

![flip2](https://user-images.githubusercontent.com/19948348/155089681-b4e1447f-938a-4df0-a255-1a9cb2cf069b.gif)

 
If you want to reproduce the problem:
https://drive.google.com/file/d/1xfBoOulvFeRzaAjDpCfalMuFsHyyEfqa/view?usp=sharing

**Comment by ruin1990** [comment]
> By the way, next update you could add the option of multiple shortcuts for the same function:

Thanks for your suggestion, I have updated it.

> Changing the subject, I wanted to know the reason behind not automatically flipping the card that has MathJax blocks?

Oh, when there is mathjax, the automatic flipping is very pitted, because the color changes to the original color after flipping over, instead of class="cloze". 

Sometimes I can't remember which formula is the cloze of this card. If this card has more cloze.

> After changing
if(cloze_num<=0 && !hasScrollbar() && have_mathjax_content==false) to if(cloze_num<=0 && have_mathjax_content==false)
it worked fine again:

In the same way, I also judged that if there is a scroll bar and it will not be automatically flipped, it must be clicked once more.
You can directly remove the judgment of the scroll bar. This is mainly because when you turn the page on ios and android, you will return to the beginning of the page, so I often can't see what the last cloze answer is.

> I use a script to randomize lists, and I was having a problem revealing these randomized lists, they weren't revealed in order:

Randomness is my problem. I didn't consider your situation. My previous logic was to traverse every time I pressed it, which was inefficient, so I directly made an array of cloze_objs when the page was loaded. So, if your random order is after mine, that might be your code's problem. You can put the part generated by the cloze_objs array behind your code logic, so that you can avoid this problem, or you can use the previous logic directly. My new logic is mainly for convenience. Scroll down, I still have optimization ideas in this part to see how it is compatible with your situation.

In the end, I may change the logic of reveal next and cover previous. Maybe I should add a new state such as flag, instead of only on and off states to represent each cloze. This may need to be considered carefully before doing it.

**Comment by huandney** [comment]
Thanks for the clarifications!
